apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elasticsearch.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.elasticsearch.name }}
    spec:
      containers:
        - name: {{ .Values.elasticsearch.name }}
          image: {{ .Values.elasticsearch.image }}
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: "single-node"
          resources:
            {{- toYaml .Values.elasticsearch.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.elasticsearch.name }}
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200