apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.fluentbit.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.fluentbit.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.fluentbit.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.fluentbit.name }}
    spec:
      containers:
        - name: {{ .Values.fluentbit.name }}
          image: {{ .Values.fluentbit.image }}
          ports:
            - containerPort: 2020 # healthcheck
            - containerPort: 2021 # metrics
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config
              mountPath: /fluent-bit/etc/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: fluent-bit-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: {{ .Values.namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  parsers.conf
        storage.path  /tmp/flb-storage
        storage.sync  normal
        storage.checksum off
        storage.backlog.mem_limit 5M

    [INPUT]
        Name           tail
        Path           /var/log/containers/*_elasticsearch_*.log
        Parser         docker
        Tag            kube.*
        Refresh_Interval 5
        storage.type   filesystem
        inotify_watcher false

    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_Tag_Prefix kube.var.log.containers.

    [OUTPUT]
        Name           es
        Match          *
        Host           elasticsearch
        Port           9200
        Index          logs
        Type           _doc

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L