replicaCount: 1
namespace: springboot-dummy-namespace

image:
  repository: ederv/learning-azure
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080
  nodePort: 8085

containerPort: 8080